### PR TITLE
Add cli.SwalkerWrite helper

### LINKED ISSUE #673: Unable to set numeric properties with --master-set, --node-set, --set
```
$ kubicorn create andy -S andy -p aws -N serverPool.minCount=2
2018-08-28T09:38:56-04:00 [✖]  Invalid --set: cannot write string to field MinCount(int) : 2
```

The `swalker` library doesn't handle string-to-numeric conversions when setting.

Any thoughts on how to proceed? Should we try to do a PR to `swalker`, find another library, or write our own?

@kris-nova

### PR DESCRIPTION
**Pull request by ncdc**
Add cli.SwalkerWrite helper to handle conversion from string to
int/uint/bool types.

Fixes #673 

Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

### CODE REVIEW

**Comment by xmudrii** [comment]
@ncdc This looks good to me. Thanks for the contribution! Can you please fix the CI failures, so I can merge the PR?

The license headers seem incorrect for `pkg/cli/swalker.go` and `pkg/cli/swalker_test.go` files. As a workaround, you can remove the headers from those files and then use the `update-headers` make target to generate them.

**Comment by ncdc** [comment]
@xmudrii thanks. The headers script has 2017 hard-coded. Let me see if I can fix that 😄

**Comment by ncdc** [comment]
@xmudrii ptal!

**Comment by xmudrii** [comment]
@ncdc Thank you so much for the fix! This looks awesome!

**Pull request merged**
