### PR TITLE
panic fix for ovh

### PR DESCRIPTION
**Pull request by xmudrii**

### CODE REVIEW

**Comment by licarth** [comment]
Yes, but now fails later in router.go when assigning providerConfig.Network.InternetGW.Identifier and providerConfig.Network.InternetGW.Name

**Comment by licarth** [comment]
And when I do comment those lines, I get an error later : 
```
2018-07-30T16:22:48+02:00 [ℹ]  Selected [fs] state store
2018-07-30T16:22:48+02:00 [ℹ]  Loaded cluster: ovh
2018-07-30T16:22:48+02:00 [ℹ]  Init Cluster
2018-07-30T16:22:48+02:00 [ℹ]  Query existing resources
2018-07-30T16:22:50+02:00 [ℹ]  Resolving expected resources
2018-07-30T16:22:50+02:00 [ℹ]  Reconciling
2018-07-30T16:22:50+02:00 [ℹ]  Using existing KeyPair [ovh]
2018-07-30T16:22:52+02:00 [✔]  Created Network [cc9b458d-9e50-41ed-a365-8f4868fe3149]
2018-07-30T16:22:54+02:00 [✖]  Error during apply of atomic reconciler, attempting clawback: Public network not found
2018-07-30T16:22:54+02:00 [!]  
2018-07-30T16:22:54+02:00 [!]  Attempting to backtrack and cleanup created resources.
2018-07-30T16:22:54+02:00 [!]  
2018-07-30T16:22:55+02:00 [✔]  Deleted Network [cc9b458d-9e50-41ed-a365-8f4868fe3149]
2018-07-30T16:22:55+02:00 [✖]  Unable to commit state store: Nil cluster spec
```

**Comment by xmudrii** [comment]
@licarth Thank you so much for the help! I'm bit busy at this moment, but I will do my best to get back to the issue later today or tomorrow.

I'll update you once I find the possible fix. I need to go through code to see is there something strange.

Thank you so much for all the help so far!

**Comment by licarth** [comment]
Alright, thanks for your help and speak later !

**Pull request merged**
