### PR TITLE
Fixing version command

### LINKED ISSUE #593: Improve GetVersion() logic
Once we start publishing releases, current [`GetVersion()`](https://github.com/kubicorn/kubicorn/blob/master/cmd/version.go#L67) is not going to work, because this assumes users have installed and configured Go environment, and they have `kubicorn` cloned.

A potential solution to this is to compile-in version using compiler flags when we build binaries.

### PR DESCRIPTION
**Pull request by kris-nova**
closes #593

### CODE REVIEW

**Comment by nrb** [comment]
Do we need to set the `LDFLAGS` vars? Here's how Ark does it in their build script.

https://github.com/heptio/ark/blob/master/hack/build.sh#L52

**Comment by kris-nova** [comment]
Instead of defining LDFLAGS I just munged all of the `go build` stuff into a single var in https://github.com/kubicorn/kubicorn/pull/601/commits/b9068155cf1d2a47e159b1dda9d0dd1c5c197dce

Should fix the problem 😄

**Comment by kris-nova** [comment]
Do we have a preference for LDFLAGS - I have no strong opinions here

**Comment by nrb** [comment]
> Do we have a preference for LDFLAGS - I have no strong opinions here

I don't.

**Pull request merged**
